[package]
name = "bsec"
version = "0.1.0"
authors = ["Jan Gosmann <jan@hyper-world.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bme680 = { version = "0.5.1", optional = true }
embedded-hal = { version = "0.2.5", optional = true }
libalgobsec-sys = "0.1.0"
nb = "1.0.0"

[dev-dependencies]
bme680 = "0.5.1"
embedded-hal = "0.2.5"
serial_test = "0.5.1"

[features]
use-bme680 = ["bme680", "embedded-hal"]
test_support = []

[package.metadata.docs.rs]
features = ["use-bme680"]
